version: 2

models:

  - name: int_energy_weather
    columns:
      - name: household_id
        tests:
          - not_null

  - name: int_energy_grid
    columns:
      - name: household_id
        tests:
          - not_null

  - name: int_energy_tariff
    columns:
      - name: household_id
        tests:
          - not_null